### ISSUE TITLE
importCSS causes 'Flash of Unstyled Content'

### ISSUE THREAD

**Issue by edude03** [faceyspacey/react-universal-component#52] opened 2017-09-25 19:38 UTC
Hello, 

First of all, I want to say thanks for the plugin, it works really well :)

One issue I'm having with the approach to loading CSS is that it seems to inject the name of the CSS into the header of the page when the module loads, causing the CSS to be loaded asynchronously, and thus causing the page to be unstyled until the css is loaded.

I'm wondering if it would make more sense to have importCss read in the CSS file and inject it into the head of the document instead like isomorphic-style-loader does?

**Comment by faceyspacey** [comment] 2017-09-26 02:47
Having that option would be nice, especially on first load. Well, maybe only on first load, as it would mean additional files don't need to be fetched. People seem to be torn which is better. There's tradeoffs to each. That said, on user Navigation, the file needs to be fetched no matter what, do it makes no difference if raw CSS is embedded in the page or link to an external stylesheets.

But maybe I'm missing something about the "name" being in the page before the CSS is loaded??

That all said there shouldn't be an unstyled moment. Perhaps the issue is something else. The CSS should be fully resolved on the page before the new js re-renders.

**Comment by edude03** [comment] 2017-09-26 16:00
Hmm, maybe I'm not explaining it well, but if you have a look at the importCss babel plugin (also sorry, I probably should have commented on that repo instead) https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/importCss.js#L31

You'll see what it does is adds the names of the css chunks to a script tag, then when the page loads it injects a <link> tag into the header to fetch that CSS file. 

The problem I'm having with that is that the CSS file has to download seperately from the HTML, and thus the page is unstyled until that file is loaded.

Instead, I'd prefer if the CSS was inlined into the page.

**Comment by faceyspacey** [comment] 2017-09-26 23:46
There shouldn't be any HTML on the page until both the new files are loaded. The way the system works is it gets both the js file and the CSS file and waits until they are loaded before resolving Promise.all. After that React Universal Component finally renders the new page. Your CSS should only correspond to elements in the new js component and its children, preferably using CSS modules.

It shouldn't make a difference if it was inlined or not. On initial load of the page, there are a few performance differences, but that's not what we are talking about.

**Closed** 2017-11-11 11:18 UTC
