### ISSUE TITLE
Chunk Name Issue

### ISSUE THREAD

**Issue by chapati23** [faceyspacey/react-universal-component#28] opened 2017-08-18 12:48 UTC
Hi James :)

I just upgraded to the glorious new syntax
```js
const UniversalComponent = universal(
  ({ page }) => import(`../../pages/${page}`),
  {
    minDelay: 500,
    loading: PageSpinner,
    error: NotFound
  }
)
```

Unfortunately I'm running into a weird issue with chunk names which causes this:

![image](https://user-images.githubusercontent.com/117495/29459366-8f421704-8423-11e7-83fc-1c49f4ab7fea.png)

The issue seems to be that webpack generates weird chunk names probably because of some hardcoded default value somewhere:

![image](https://user-images.githubusercontent.com/117495/29459406-ae925966-8423-11e7-91b9-45281c6ecdd1.png)

After switching back to the old, boring and verbose syntax:
```js
const UniversalComponent = ({ page, isLoading }: Props) => {
  const Component = components[page] || NotFound
  return <Component isLoading={isLoading} />
}

const components = {
  Overview: universal(() => import('../../pages/Overview'), {
    minDelay: 500,
    loading: PageSpinner
  }),
  Invest: universal(() => import('../../pages/Invest'), {
    minDelay: 500,
    loading: PageSpinner
  }),
  Portfolio: universal(() => import('../../pages/Portfolio'), {
    minDelay: 500,
    loading: PageSpinner
  }),
  NotFound
}
```

…it works fine again and webpack generates correct chunk names:

![image](https://user-images.githubusercontent.com/117495/29459447-e15f9b38-8423-11e7-90bf-f5893d3f601d.png)

I'm 90% sure the issue is that my folder structure is:
```
- components
    - Overview
        - index.js
        - styles.css
```

and I guess you are expecting:
```
- components
    - Overview.js
```

I've tried various paths in the universal component, e.g.:
* ```import(`../../pages/${page}`)```
* ```import(`../../pages/${page}/index`)```
* ```import(`../../pages/${page}/index.js`)```

But none seem to work.

Any idea what might go wrong here and whether `react-universal-component` or `webpack-flush-chunks` is to blame?

**Comment by faceyspacey** [comment] 2017-08-18 12:53
it's in the index.js file, and it's actually a webpack issue. webpack generates chunks with hyphens at the end when you use dynamic expressions within import (i.e. ```import(`./${page}`)```) and in the the folder you import from is both an index.js file and named files.

In short, if you want the problem solved quickly, don't use index.js files for what you want to import.

Notice the hyphens added to the names of files. Webpack is doing that. Look into the transpiled code and you will see that Universal doesn't add hyphens. Well, you'll have to open node_modules/babel-loader and log where it has `result.code`. Then in your terminal a lot will be spit out. You gotta search your terminal for something like `Promise.all` generated by the babel plugin, and then you will see that I did not generate anything with hyphens at the end.

I've only seen this in other people's code. I'd love if it someone analyzed it completely and reported it to webpack. 

You can reproduce this without my plugin by doing the magic comment i create that ends in `[request]` (which indicates to create a dynamic chunkName. Do that on a folder that has both named files and an index.js file and you will see the problem.

**Comment by faceyspacey** [comment] 2017-08-18 12:56
but u did guess right. if u change ur folder structure (to older more typical way), it will just work. the grouping thing will require a PR to webpack. We need that issue into webpack tho. My guess is I'll probably be the one who ends up fixing it. I'm not the one to supply the issue however, as I have no apps currently this way.

**Comment by faceyspacey** [comment] 2017-08-18 13:06
here's what the issue to post looks like (feel free to copy/paste). Basically i want them to know im fixing other people's actual issues, not just mine. Here we go:


when using:

```js
import(/* webpackChunkName: 'asyncComponents/[request]' */ `./asyncComponents/${name}`)
```

and when your folder structure is this:

-asyncComponents
  -Post
     -index.js
     -styles.js
     -etc.js
  -Item
     -index.js
     -styles.js
     -etc.js

You would expect the imported chunk name to be `asyncComponents/Post-index`. Instead it's `asyncComponents/Post-`.

`styles.js` for example gets a chunk named: `asyncComponents/Page-styles`.


---

and actually, shit. The truth is the way webpack works is just not good for this grouping structure. The reason is you don't want chunks created for `styles.js` You only want the `index.js` which imports them. As you know, webpack recursively finds all potentially matching files and creates chunks with them as entry points. It's just not gonna work--not without a regex. And `import` doesn't support a regex like `require.context`. It's gonna make chunks out of every file in `Post`, `Item`, `Portfolio`, whatever folder you throw at it.

So even if the above was fixed and it was properly named, your compiler is now doing tons of every work, and you will be waiting unnecessarily. I mean it could end up taking more time than had all those extra chunks not be made. Maybe multiple times more time--after all you're not creating a shitload of unnecessary chunks.

**Comment by faceyspacey** [comment] 2017-08-18 13:11
still please post the issue tho. just let em know the hyphen shouldnt be there. If we had that, it work. Just check the output of `flushChunkNames`. You should see `pages/Portfolio`.  Let me know if that's not the case.

Cuz then at least, u can get this working and wouldnt face this problem, and then decide on ur own to ***optimize*** to not have unnecessary chunks built. That's ideal here.

**Comment by faceyspacey** [comment] 2017-08-18 13:12
also ideally in my opinion, there should be no hyphens at all. styles should come out as this:

`pages/portfolio/styles`

**Comment by faceyspacey** [comment] 2017-08-18 13:17
matter fact i think we could solve it.

check it. webpack decide it has to add something for `index`. so they chose a hyphen. im not sure why they couldnt do just do `index` but there may be a reason. there also may not be.

either way, if we change this line in webpack-flush-chunks:

https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/flushChunks.js#L206

to:

```js
const entryToFiles = entry => assetsByChunkName[entry] || assetsByChunkName[entry+'-']
````

it should be able to find it. you also have to change the warning a few lines above that does a similar check. 

if u could do me a favor and open up node_modules/webpack-flush-chunks/dist/flushChunks and try that change, I'd greatly appreciate it.

It's a small change that wont hurt performance on the server. So maybe I'll just do it (or u via a PR if u want), so that people at least dont fall on these hiccups and blame *Universal*. :)

**Comment by faceyspacey** [comment] 2017-08-18 14:31
Ok, by the way i updated webpack-flush-chunks to reflex the fix for this:

https://www.npmjs.com/package/webpack-flush-chunks

Let me know if works on your end.

**Comment by chapati23** [comment] 2017-08-18 18:36
o_O !?

3 hours AFK and I come back to this. Updated flush-chunks => works like a charm.

dare I say, you're fucking awesome 🙌

**Comment by chapati23** [comment] 2017-08-18 18:37
am on a weekend trip right now, didn't 100% understand what the latest conclusion now is: should i still go ahead an create an issue over at webpack on monday?

**Comment by faceyspacey** [comment] 2017-08-18 18:37
Thanks brother. Keep in mind ur still creating unnecessary chunks which wastes built time. Look into the context replacement plugin. U should be able to filter out the chunks u don't want made, ie for styles.css. Let me know if it works.

**Comment by faceyspacey** [comment] 2017-08-18 18:38
Yea create an issue. They should know.

**Closed by faceyspacey** 2017-08-18 18:38 UTC

**Comment by chapati23** [comment] 2017-08-26 12:18
➡️ https://github.com/webpack/webpack/issues/5575
