### ISSUE TITLE
chunk not available for synchronous require yet

### ISSUE THREAD

**Issue by re6exp** [faceyspacey/react-universal-component#128] opened 2018-06-26 15:04 UTC
When I try to set `webpackChunkName` in `import()`, I get this in linux console:

<details><summary>trace (Click to show)</summary>
<p>

```

chunk not available for synchronous require yet: /components/Home: Cannot find module '/components/Home' Error: Cannot find module '/components/Home'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at requireById (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/react-universal-component/dist/utils.js:59:19)
    at tryRequire (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/react-universal-component/dist/utils.js:45:12)
    at requireSync (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/react-universal-component/dist/requireUniversalModule.js:42:37)
    at UniversalComponent.componentWillMount (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/react-universal-component/dist/index.js:193:23)
    at processChild (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/react-dom/cjs/react-dom-server.node.development.js:2167:16)
    at resolve (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/react-dom/cjs/react-dom-server.node.development.js:2061:5)
    at ReactDOMServerRenderer.render (/home/anton/Documents/workspace-sts/nodejs-spring-cloud-app-boilerplate/node_modules/react-dom/cjs/react-dom-server.node.development.js:2380:22)

```
</p>
</details>
<br/>
and shows an error `error: serverRenderer is not a function`.
<br/>

If I do not try to change chunk name, it works, but the error is showed in console anyway.

specs:
-  "webpack": "^4.12.0",
-  "webpack-hot-server-middleware": "^0.5.0",
- "babel-plugin-universal-import": "faceyspacey/babel-plugin-universal-import#webpack-4",
- "webpack-flush-chunks": "^2.0.1-beta.1"

And most interesting is: when I start dev server whithout commented `webpackChunkName` instruction, but change them on the fly, without restart server (HMR works), no errors shows in browser, only console always contains that error. In any case.

May be, my server setup has smth wrong...

**Comment by re6exp** [comment] 2018-06-27 12:53
https://github.com/faceyspacey/react-universal-component/issues/104

**Comment by faceyspacey** [comment] 2018-06-27 23:40
@ScriptedAlchemy thoughts?

**Comment by ScriptedAlchemy** [comment] 2018-06-27 23:42
Hmmm interesting. I’ll have to check this one and verify if there’s anything. Looks related to Babel universal if anything

**Comment by ScriptedAlchemy** [comment] 2018-06-28 04:19
Give me till Monday, I’m in the middle of moving coasts. My company issued machine goes back tomorrow and I gotta pack. I’ll have a rig up next week Monday and run through the backlog here. Sorry for the delays guys ❤️

**Comment by re6exp** [comment] 2018-06-28 10:18
I get it, no problem. I'll been waiting, but until that, I'm going to check what I can in my own code. I've changed many things in the project, may be I missed smth.

**Comment by re6exp** [comment] 2018-06-29 10:16
The problem with trace goes out after I completely remove `externals` from the server config.
But the problem with magic comments stays, if I try to turn them, server builds Home.js instead of server.js 8-/

**Comment by ScriptedAlchemy** [comment] 2018-07-03 02:10
Half way there man, 2 more days 😂

So I had this issue as well. What I did was create like a utility component. Essentially, a workaround is instead of using universal HOC on many pages, create another JSX file that accepts a prop. Then, use ignore-loader so that it’s not bundled in. 

I’ll be able to look closer at this once I’m set Up. Again sorry for such delays

**Comment by re6exp** [comment] 2018-07-03 08:18
Does using the wrapper described above lead to build separate chunks?

**Comment by ignatiusreza** [comment] 2018-07-25 10:32
Hi guys, sorry for jumping in.. any progress on this front?

we're having similar issue.. looking into it, it does seems like it's an issue with the babel plugin.. the source file that we have looks like:

```js
import universal from 'react-universal-component';

export default universal(import(/* webpackChunkName: 'routes/home' */ './main'));
```

which got compiled into

```js
// some boilerplate + react-hot-loader-stuff

var _default = react_universal_component__WEBPACK_IMPORTED_MODULE_2___default()(babel_plugin_universal_import_universalImport__WEBPACK_IMPORTED_MODULE_1___default()({
  id: './main',
  file: '/webpack/src/routes/home/index.js',
  load: function load() {
    return Promise.all([Promise.all(/*! import() | routes/home */[__webpack_require__.e("entities~routes/activities~routes/cart~routes/home~routes/kitchen-sink~routes/things-to-do"), __webpack_require__.e("routes/activities~routes/home~routes/kitchen-sink~routes/things-to-do"), __webpack_require__.e("routes/cart~routes/home~routes/kitchen-sink~routes/things-to-do"), __webpack_require__.e("routes/home~routes/things-to-do"), __webpack_require__.e("routes/home~routes/kitchen-sink"), __webpack_require__.e("routes/home")]).then(__webpack_require__.bind(null, /*! ./main */ "./routes/home/main.jsx"))]).then(function (proms) {
      return proms[0];
    });
  },
  path: function path() {
    return path__WEBPACK_IMPORTED_MODULE_0___default.a.join(__dirname, './main');
  },
  resolve: function resolve() {
    return /*require.resolve*/(/*! ./main */ "./routes/home/main.jsx");
  },
  chunkName: function chunkName() {
    return 'routes/home';
  }
}));

/* harmony default export */ __webpack_exports__["default"] = (_default);
;

// some react-hot-loader-stuff
```

and from the babel plugin [readme](https://github.com/faceyspacey/babel-plugin-universal-import#what-it-does), it sounds like `./routes/home/main.jsx` in both `load` and `resolve` should have been `./main.jsx` instead?

**Comment by ScriptedAlchemy** [comment] 2018-07-26 02:00
Hi guys, you can check out the universal demo, ive updated it for RUC 3.

I am currently having some challenges around the dynamic import (RUC) Sitting in the directory itself. 

What happens is it seems to swallow itself on the server side, what I've been doing is moving it up one level and importing it back down.  I create a utility file and it sits outside the directory I plan to dynamically load.


Any help would be appreciated on this one

**Comment by ScriptedAlchemy** [comment] 2018-07-26 02:02
@ignatiusreza chunknames with slashes get converted to dashes, might be the problem you are seeing inside of RUC?

**Comment by ignatiusreza** [comment] 2018-07-26 06:19
> I am currently having some challenges around the dynamic import (RUC) Sitting in the directory itself.

This sounds like the issue that we're facing.. our directory structure looks like

- routes:

  - home:

    - index.js
    - main.jsx

  - other routes...

and we have `universal` importing `main.jsx` from `index.js`.. i'll try to see if restructuring where universal is sitting solve it..

**Comment by ScriptedAlchemy** [comment] 2018-07-26 13:00
It’s annoying bit an effective fix, move the utility up one level and point it at the directory. 

I’m going to try and rally some devs to help me track down the issue

**Comment by ignatiusreza** [comment] 2018-07-27 01:44
we managed to figure out what went wrong.. part of it is due to some (quite silly) misconfiguration.. leaving it here in case other face similar issue..

what we misconfigure:

- `output.path` for client and server MUST be different.. didn't notice this at first and we have client bundle overriding the server bundle.. :man_facepalming: 
- we stumble into [this issue](https://github.com/webpack/webpack/issues/1599), and setting `{ node: { dirname: false } }` fix it.. before this `path__WEBPACK_IMPORTED_MODULE_0___default.a.join(__dirname, './main');` return incorrect value since `__dirname` somehow get overwritten to `/`.. not sure if this is due to another misconfugration elsewhere?

we also need to make some changes in the babel plugin.. the main issue is, the generated `path` disregard the given `chunkName`, even though webpack compiled output us it to name the generated output file.. I opened https://github.com/faceyspacey/babel-plugin-universal-import/pull/63 to show what I meant.. but, i'm honestly not sure if this is the right things to do.. :sweat_smile:

**Comment by ScriptedAlchemy** [comment] 2018-07-27 04:03
Wait wait wait. Is this in regards to the issue I identified of having to put RUC utilities one folder higher!?!

**Comment by ScriptedAlchemy** [comment] 2018-07-27 18:55
Im gonna test this out locally!

**Comment by ScriptedAlchemy** [comment] 2018-07-30 20:41
@ignatiusreza So it does seem you do indeed solve the directory issue, Well done. But i am getting a few other issues. 

Let me try implementing this into a repo so you can see.

**Comment by ScriptedAlchemy** [comment] 2018-07-30 22:52
Hmm @ignatiusreza do you have an example repo of this?

**Comment by ignatiusreza** [comment] 2018-07-31 00:27
I don't have one readily available, as the project that i'm working on is not open source.. but, I guess, I can try to get one out.. it might takes a few days though, if that's okay..

**Comment by ScriptedAlchemy** [comment] 2018-07-31 00:40
It’s a tricky one to test against. I’ll need to actually put it in npm under some tag so I can verify. It’s really hard to determine with symlinks. They often give me problems in the build so I can’t sign off without really knowing. It seems as if the Change is mostly a refractory. The part I’m interested in is how you are keeping RUC in the same folder as the stuff you import without the server build re among the file something really starange

**Comment by ScriptedAlchemy** [comment] 2018-07-31 06:24
@rherwig can you send me a example repo (you user sounds familiar so I'm sorry if we had this chat before)

**Comment by rherwig** [comment] 2018-07-31 06:29
@ScriptedAlchemy The issue of @manish4781 can be found [here](https://github.com/rherwig/template-react-16-ssr/issues/28). He is using the latest master of template-react-16-ssr.

However, I did not currently reproduce the issue myself.

**Comment by ScriptedAlchemy** [comment] 2018-07-31 06:33
@rherwig ahh thank you, its could likely by a yarn.lock or package-lock.json file messing with him?

I discovered a few React-Static issues related to that

**Comment by ScriptedAlchemy** [comment] 2018-07-31 06:43
Hmmm @rherwig If you are not able to then I'm inclined to dedicate my efforts into other areas of this project in desperate need of upgrades.  One being a been call to developers who want to help us out with getting an alpha release of Rudy #justSaying

**Comment by ignatiusreza** [comment] 2018-07-31 10:18
@ScriptedAlchemy so I created a sample app in https://github.com/ignatiusreza/react-universal-component-128 and while working on it, I realized what you meant by `chunknames with slashes get converted to dashes`.. :man_facepalming: 

our project are still using react-universal-component v2.9.0, hence chunk names doesn't get dasherized.. i'll try to update the sample repo to v3.0.0 and test how it behave.. for now the sample repo is up if you want to see how the setup is..

one thing that concern me is you mentioned that [`strings like: "components/thing/other" they were impossible to flush out`](698bd2f660088c728f80b0b68f62166128260657).. but, it seems to be working just fine in the sample project I made?

**Comment by ignatiusreza** [comment] 2018-08-01 05:45
updated the sample repo to v3.0.0, and everything is still working (even with RUC sitting in the same folder)..

also did some more investigation I realized that faceyspacey/babel-plugin-universal-import#63 is a complete misdirection (sorry for the noise :sob:).. the key take away here are:

- everything from the universal family [must not be marked as `externals`](https://github.com/ignatiusreza/react-universal-component-128/blob/509c201c9372d246d7c77088ba90b665d5fe7f0d/webpack.config.server.js#L10-L16)

- server must generate only 1 chunk; so `new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 })` is a hard requirement

**Comment by ScriptedAlchemy** [comment] 2018-08-01 05:54
@ignatiusreza

> 
one thing that concern me is you mentioned that strings like: "components/thing/other" they were impossible to flush out.. but, it seems to be working just fine in the sample project I made?


Either we were miss-communicating, or that message was old. I specifically did that while dash to slashes thing in order to get access to chunknames, you are indeed and should be able to do exactly that!

Now when it comes to externals, things get a lil tricky. If you check my profile, you'll see 2 things

- Webpackery
- moduleraid

Those things are designed around chunk sharing and injection within webpack.

Can you have some file run through the build where your external needs to run. Like literally just another script on the page or something. 

You can share other resources in other chunks from other builds (shhhhhh) it's true!!

At least in my setups (remember module raid and webpackery) but i think you should be able to just load a chunk within a universal app, and it will be available to other builds. 

Might be an issue if the hashes are different but give it a try

**Comment by ScriptedAlchemy** [comment] 2018-09-11 22:08
@re6exp is this still a valid issue, given the update we have?

**Comment by re6exp** [comment] 2018-09-12 07:03
Yes, it is. But I'm not sure what is the cause. May be, my configuration is
wrong.

12 сент. 2018 г. 1:08 AM пользователь "Zack Jackson" <
notifications@github.com> написал:

@re6exp <https://github.com/re6exp> is this still a valid issue, given the
update we have?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/faceyspacey/react-universal-component/issues/128#issuecomment-420442759>,
or mute the thread

**Comment by ScriptedAlchemy** [comment] 2018-09-12 20:49
going to close this out for the time being. I am looking into a solution for flushing chunks with slashes.

**Closed by ScriptedAlchemy** 2018-09-12 20:49 UTC
